### ISSUE TITLE
node error when trying to create a new activedoc

### ISSUE THREAD

**Issue by lucamaf** [3scale/3scale-cli#36]
here is the command:
`3scale-cli activedocs create -f cortica.json`

here is the error:
```
ERROR encountered: undefined
(node:32607) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Server responded with status code 422 undefined
```

and the swagger is here:
https://app.box.com/s/5p9dr7rua19ebam1cvas0hmchcgtdul8

**Comment by picsoung** [comment]
hi @lucamaf 
I could not reproduce your issue

using the following command it worked great

`3scale-cli activedocs create -f swagger.json`
