### ISSUE TITLE
RFE - Support to directly urls as argument

### ISSUE THREAD

**Issue by hodrigohamalho** [3scale/3scale-cli#42]
3scale-cli import <spec_type> -f /path/to/apidefinition -s SERVICE_ID

The -f argument could accept a url to the file, eg:

3scale-cli import <spec_type> -f http://someurl.com/api/apidefinition.json -s SERVICE_ID

**Comment by picsoung** [comment]
Did you try ?
I remember it was working last time I have tried  ;)

**Comment by hodrigohamalho** [comment]
Yes, it is working.

TY ;)
