### ISSUE TITLE
interactive questions are a problem for unattended execution (devops tasks)

### ISSUE THREAD

**Issue by agustinbs** [3scale/3scale-cli#57]
I am quite new to nodejs so I might be missing some obvious solutions, if that was the case please be patient with me.
I am using 3scale-cli as a the way to achieve automation on deployment on 3scale gateways. I could have used 3scale REST API if I just had the corresponding swagger file, then with Swagger Codegen I was set to create a client SDK, but that swagger file is nowhere to be found. The product source code in ruby does have the tags for https://github.com/solso/source2swagger, but I do not know how to use it properly and imagine that swagger should be public somewhere? I just could not find it.
Too bad, I based my automation scripts on calling 3scale-cli and data scraping the output to get the ids of the different entities created or listed.
Then I found that some commands require interactive input via 'Inquirer.js'. Initially only 'config' was a problem, I coded an extra command to configure from script with no keyboard input.
But after the last changes I find that also the 'import' command now has interactive prompt.
Unless there is some trick to specify input to be accepted by Inquirer with no human intervention, may I suggest that all functionalities of this tool are made compatible with unattended execution? Many thanks  in advance for your suggestions and feedback!

**Comment by picsoung** [comment]
Hi @agustinbs 

Thanks for your comments. I am sorry you are having troubles with this tool.

The addition of interactive questions is meant to make it easier to use the tool, and be guided in the process.
But you can skip those questions by passing directly parameters.

I have opened a PR to add a parameter that will skip endpoint selections.
here is the doc: https://github.com/3scale/3scale-cli/pull/60/files#diff-bf10c0cc488c2d517236993741bbd468R49

let me know what you think

**Comment by agustinbs** [comment]
Hi @picsoung,

Sorry it took a while to get back to you. I was able to test with the new version, and the changes definitely allow for the unattended use that I need. I still have an extra issue, it has to do with the behavior of the 'config' command, which from the beginning requires user interaction (again, the 'Inquirer'). I forgot to mention that for this I made a change on my local copy of the tool, I wrote an extra 'configure' command that works akin the rest of commands, i.e. you can specify the parameter values. Further to this, I modified both 'config' and my new 'configure' (both do the same thing) so as to care for a system variable, which I called 'THREESCALECLICONFIGPATH '.
So in 'config.js' from line 11, it reads like this:

var env = process.env;
var configDirPath = env.THREESCALECLICONFIGPATH || osHomedir();

nconf.file({ file: configDirPath +"/.3scale/credentials.json" });
nconf.load();

The reason to allow for choosing the directory for the configuration is that, when the tool is executed in an automation server (Jenkins in my case), there could be interference between Jobs being run by the same user ('jenkins') that intend to interact with different instances of 3scale. So in those Jobs, I am assigning a value for THREESCALECONFIGPATH somewhere within Jenkins workspace for that job.

This is similar to the behaviour of 'kubectl' CLI, which cares about the envvar KUBECONFIG to pick where to place its session context info.  Now, since we are at comparing, I also noticed that in the 'credentials.json' the access token (which gives full access to anything in 3scale), appears in plain text. I wonder if that could be a security vulnerability, it looks to me as far too easy for someone to write a malicious script that would chase after that file in someone else's computer and obtain the token.
Shouldn't it be hashed or/and time limited?

Also, if you just type the 'config' command in the CLI, the current values appear, so someone getting keyboard access to a computer where 3scale was accessed at some point, can easily obtain the api key. Again, this looks like too easy for any 'bad people' out there.

**Comment by agustinbs** [comment]
And, an extra oddity I found, but I am not sure if it would call for a change on the CLI tool, or somewhere else.  The 'command-proxy.js', both in code and in its documentation, makes you believe that by specifying an option "-S <sandbox_url>" you will be able to modify the base URL for the sandbox deployment of the gateway. However in the version of 3scale that I have, this does not work, and in my view it does not work simply because the related REST API does not accept that parameter. So the CLI tool calls the REST API with that value, but 3Scale ignores it.  This looks to me more like a bug in the API rather than 'works as designed', since from the web portal you can certainly change that value, so I would find no reason to have that change prevented via REST.
In my view, fixing this would require fixing 3Scale API rather than the CLI, but I might have gotten all wrong, or this has been already fixed in newer versions. If you happen to take a look on it, I'll be glad to know about your findings.
