### ISSUE TITLE
extra two-digit number appended to service name

### ISSUE THREAD

**Issue by agustinbs** [3scale/3scale-cli#58]
Entering '3scale-cli services create --serviceName mytest', you get a feedback message 'Service with name mytest created. However the actual name of the service created is something like 'mytestXX' where XX is a random number. The reason for this can be seen directly in the source file 'services.js', line 11 that reads:
"var n = name+Math.floor((Math.random() * 50) + 10)".

**Comment by picsoung** [comment]
Hi @agustinbs 

This problem has been reported few times, the idea was to avoid a collision on system name when people were importing the same swagger spec multiples times.

I have opened a PR that should solve this issue if you specify a serviceName #59

Hope it fits what you had in mind

**Comment by agustinbs** [comment]
Yes, current behaviour suits me better. But I have to point out that I never aimed for 'incremental' updates since I was unsure how could it handle or distinguish things like keeping a method name and changing url path, vs assigning a new name to an already existing url path, and so forth.... I deemed it safer for my automation scripts, to erase the whole service, and import the swagger and define everything else (client apps, application plans) fresh new.

**Comment by picsoung** [comment]
Yes, the collision could happen at another level. It may return an error if a method already exists with the same name.

Deleting everything would work fine, but I don't think we will implement it natively in the CLI.
