### ISSUE TITLE
Creating new limit the value always set to 1  

### ISSUE THREAD

**Issue by sgutierr** [3scale/3scale-cli#64]
To reproduce the issue try to create a limit setting the value different 1, for instance:
 3scale-cli limits create --service 6 --appplan 13 --metric 14 --period week --unit 0

I thought the parameter value is missed in command-limits.js or it's using "unit" parameter instead. Also it seems the place where is set to 1 is: file limits.js file 17

**Comment by picsoung** [comment]
Solved by #65 and #66 
Thanks @sgutierr
